# use java support
language: java
jdk: openjdk11

# run in container
sudo: false

# use linux as operating system
os: linux

# Install xmlstarlet
addons:
  apt:
    packages:
      - awscli

# Do not run travis install step `./gradlew assemble`
install: true

# Assemble jars
script:
  - ./gradlew --refresh-dependencies clean assemble

cache:
  directories:
    - $HOME/.gradle/caches/

deploy:
  # Deploy snapshots on every commit made to master
  - provider: script
    script: bash .ci/deploy-snapshot.sh
    skip_cleanup: true
    on:
      branch: master

  # Deploy releases on every tag push
  - provider: script
    script: bash .ci/release.sh
    skip_cleanup: true
    on:
      tags: true
